
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ReservarActividadExitoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void reservarActividadExito() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1295, 687));
    driver.findElement(By.id("btn-hora")).click();
    driver.findElement(By.cssSelector("#dd-hora > .filter-dropdown__item:nth-child(3)")).click();
    driver.findElement(By.id("btn-deporte")).click();
    driver.findElement(By.cssSelector("#dd-deporte > .filter-dropdown__item:nth-child(5)")).click();
    driver.findElement(By.id("act-A04")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#act-A04 .activity-item__lugar"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("btn-reservar")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(4)")).click();
  }
}
